name: Cache · Trivy Database
run-name: "Cache · ${{ github.event_name }} · ${{ github.sha }}"

on:
  schedule:
    - cron: "17 2 * * *"
  workflow_dispatch:

concurrency:
  group: "cache-warm-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  trivy-cache:
    permissions:
      contents: read
      actions: write
    uses: grootan-devops/github-ci-library/.github/workflows/trivy-cache.yml@dev
    secrets: inherit
    with:
      enable-java-db: false
