name: Scan · Released Image
run-name: "Scan · ${{ github.event_name }} · ${{ github.sha }}"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Released version to re-scan
        required: true
        type: string

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  init:
    permissions:
      contents: read
      actions: read
      pull-requests: read
    uses: grootan-devops/github-ci-library/.github/workflows/init.yml@dev
    secrets: inherit
    with:
      tag: ${{ inputs.tag }}
      ignore-chart: "true"

  trivy-cache:
    needs: init
    permissions:
      contents: read
      actions: write
    uses: grootan-devops/github-ci-library/.github/workflows/trivy-cache.yml@dev
    secrets: inherit
    with:
      enable-java-db: false

  image-scan:
    needs: [init, trivy-cache]
    permissions:
      contents: read
      checks: write
    uses: grootan-devops/github-ci-library/.github/workflows/scan.yml@dev
    secrets: inherit
    with:
      scan-type: image
      image-repository: ${{ needs.init.outputs.image-repository }}
      target-version: ${{ needs.init.outputs.image-tag }}
