name: Lint · Dockerfile, YAML & Docs
run-name: "Lint · ${{ github.event_name }} · ${{ github.sha }}"

on:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    permissions:
      contents: read
    uses: grootan-devops/github-ci-library/.github/workflows/lint.yml@dev
    secrets: inherit
