name: Security · Secret Scan
run-name: "Security · ${{ github.event_name }} · ${{ github.sha }}"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  secret-scan:
    permissions:
      contents: read
    uses: grootan-devops/github-ci-library/.github/workflows/secret-scanning.yml@dev
    secrets: inherit
    with:
      full-history: true
